import {
  BiHomeCircle as HomeIcon,
  BiUser as AboutIcon,
  BiCollection as ProjectIcon,
  BiCategory as DashboardIcon,
  BiBook as GuestbookIcon,
  BiEnvelope as ContactIcon,
  BiLink as LinksIcon,
  BiHistory as ChangelogIcon,
  BiBriefcase as UsesIcon,
  BiLayer as CreationsIcon,
  BiMessageSquareDetail as SmartTalkIcon,
} from "react-icons/bi";
import { PiCertificate as AchievementIcon } from "react-icons/pi";

import { MenuItemProps } from "../types/menu";

const iconSize = 20;

export const MENU_ITEMS: MenuItemProps[] = [
  {
    title: "Home",
    href: "/",
    icon: <HomeIcon size={iconSize} />,
    isShow: true,
    isExternal: false,
    eventName: "Pages: Home",
  },
  {
    title: "About",
    href: "/about",
    icon: <AboutIcon size={iconSize} />,
    isShow: true,
    isExternal: false,
    eventName: "Pages: About",
  },
  {
    title: "Creations",
    href: "/creations",
    icon: <CreationsIcon size={iconSize} />,
    isShow: true,
    isExternal: false,
    eventName: "Pages: Creations",
  },
  {
    title: "Achievements",
    href: "/achievements",
    icon: <AchievementIcon size={iconSize} />,
    isShow: true,
    isExternal: false,
    eventName: "Pages: Achievements",
  },
  {
    title: "Projects",
    href: "/projects",
    icon: <ProjectIcon size={iconSize} />,
    isShow: true,
    isExternal: false,
    eventName: "Pages: Projects",
  },
  {
    title: "Dashboard",
    href: "/dashboard",
    icon: <DashboardIcon size={iconSize} />,
    isShow: true,
    isExternal: false,
    eventName: "Pages: Dashboard",
  },
  {
    title: "Guestbook",
    href: "/guestbook",
    icon: <GuestbookIcon size={iconSize} />,
    isShow: true,
    isExternal: false,
    eventName: "Pages: Guestbook",
  },
  {
    title: "Uses",
    href: "/uses",
    icon: <UsesIcon size={iconSize} />,
    isShow: true,
    isExternal: false,
    eventName: "Pages: Uses",
  },
  {
    title: "Contact",
    href: "/contact",
    icon: <ContactIcon size={iconSize} />,
    isShow: true,
    isExternal: false,
    eventName: "Pages: Contact",
  },
  {
    title: "Links",
    href: "/links",
    icon: <LinksIcon size={iconSize} />,
    isShow: true,
    isExternal: false,
    eventName: "Pages: Links",
  },
  {
    title: "Changelog",
    href: "/changelog",
    icon: <ChangelogIcon size={iconSize} />,
    isShow: true,
    isExternal: false,
    eventName: "Pages: Changelog",
  },
  {
    title: "Smart Talk",
    href: "/smart-talk",
    icon: <SmartTalkIcon size={iconSize} />,
    isShow: true,
    isExternal: false,
    eventName: "Pages: Smart Talk",
  },
];
