-- ==========================================================================================
-- SCRIPT PEMBUATAN TABEL DAN RLS (ROW LEVEL SECURITY)
-- ==========================================================================================
-- Jalankan script ini di SQL Editor Supabase Anda untuk membuat seluruh tabel 
-- yang dibutuhkan oleh aplikasi, sekaligus mengatur sistem keamanannya.

-- 1. BUAT TABEL-TABEL APLIKASI
CREATE TABLE IF NOT EXISTS public."Profile" (
    id bigint generated by default as identity primary key,
    "fullName" text,
    name text,
    title text,
    bio text,
    email text,
    location text,
    "avatarUrl" text,
    "cvLink" text,
    github_url text,
    linkedin_url text,
    instagram_url text
);

CREATE TABLE IF NOT EXISTS public."Social" (
    id bigint generated by default as identity primary key,
    platform text,
    url text,
    icon text
);

CREATE TABLE IF NOT EXISTS public."Experience" (
    id bigint generated by default as identity primary key,
    company text,
    position text,
    period text,
    description text,
    "logoUrl" text,
    "showOnHome" boolean default true,
    "order" int,
    type text
);

CREATE TABLE IF NOT EXISTS public."Education" (
    id bigint generated by default as identity primary key,
    institution text,
    degree text,
    major text,
    period text,
    description text,
    "logoUrl" text,
    status text,
    "showOnHome" boolean default true,
    "order" int
);

CREATE TABLE IF NOT EXISTS public."Organization" (
    id bigint generated by default as identity primary key,
    role text,
    name text,
    period text,
    description text,
    "logoUrl" text,
    "showOnHome" boolean default true,
    "order" int
);

CREATE TABLE IF NOT EXISTS public."Project" (
    id bigint generated by default as identity primary key,
    title text,
    slug text,
    description text,
    "imageUrl" text,
    featured boolean default false,
    "demoUrl" text,
    "repoUrl" text,
    "projectUrl" text,
    tags text,
    category text,
    "showOnHome" boolean default true
);

CREATE TABLE IF NOT EXISTS public."Article" (
    id bigint generated by default as identity primary key,
    title text,
    slug text,
    content text,
    "imageUrl" text,
    tags text,
    excerpt text,
    "showOnHome" boolean default false,
    published boolean default true,
    views int default 0,
    comments int default 0,
    reactions int default 0,
    "readTime" text,
    "createdAt" timestamp with time zone default timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public."Testimonial" (
    id bigint generated by default as identity primary key,
    name text,
    role text,
    message text,
    "avatarUrl" text,
    rating int default 5,
    "showOnHome" boolean not null default true,
    "createdAt" timestamp with time zone default timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public."Message" (
    id bigint generated by default as identity primary key,
    name text,
    email text,
    subject text,
    message text,
    likes int default 0,
    "avatarUrl" text,
    "createdAt" timestamp with time zone default timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public."SiteSettings" (
    key text primary key,
    value text
);

CREATE TABLE IF NOT EXISTS public."Skill" (
    id bigint generated by default as identity primary key,
    name text,
    category text,
    percentage int,
    "showOnHome" boolean default true
);

-- 2. AKTIFKAN RLS (Row Level Security)
ALTER TABLE public."Profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Social" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Experience" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Education" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Project" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Article" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Testimonial" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Message" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SiteSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Skill" ENABLE ROW LEVEL SECURITY;

-- 3. BUAT POLICY (Hak Akses)
-- A. Semua tabel bisa DIBACA oleh siapapun (publik)
DROP POLICY IF EXISTS "Public Read Access Profile" ON public."Profile";
CREATE POLICY "Public Read Access Profile" ON public."Profile" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Access Social" ON public."Social";
CREATE POLICY "Public Read Access Social" ON public."Social" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Access Experience" ON public."Experience";
CREATE POLICY "Public Read Access Experience" ON public."Experience" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Access Education" ON public."Education";
CREATE POLICY "Public Read Access Education" ON public."Education" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Access Organization" ON public."Organization";
CREATE POLICY "Public Read Access Organization" ON public."Organization" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Access Project" ON public."Project";
CREATE POLICY "Public Read Access Project" ON public."Project" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Access Article" ON public."Article";
CREATE POLICY "Public Read Access Article" ON public."Article" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Access Testimonial" ON public."Testimonial";
CREATE POLICY "Public Read Access Testimonial" ON public."Testimonial" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Access Message" ON public."Message";
CREATE POLICY "Public Read Access Message" ON public."Message" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Access SiteSettings" ON public."SiteSettings";
CREATE POLICY "Public Read Access SiteSettings" ON public."SiteSettings" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Access Skill" ON public."Skill";
CREATE POLICY "Public Read Access Skill" ON public."Skill" FOR SELECT USING (true);

-- B. Siapapun bisa mengirim pesan (Guestbook)
DROP POLICY IF EXISTS "Public Insert Message" ON public."Message";
CREATE POLICY "Public Insert Message" ON public."Message" FOR INSERT TO public WITH CHECK (true);

-- C. (Opsional) Jika hanya yang sudah login yang bisa INSERT/UPDATE/DELETE selain pesan:
-- Anda dapat menambahkan RLS lanjutan jika perlu, misalnya:
-- CREATE POLICY "Admin All Access" ON public."Profile" FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- dst.
