import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./common/**/*.{js,ts,jsx,tsx,mdx}",
    "./modules/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          950: "#474100",
          900: "#756c00",
          800: "#A39600",
          700: "#d1c000",
          DEFAULT: "#fbe400",
          500: "#ffee2e",
          400: "#fff15c",
          300: "#fff58a",
          200: "#fff9b8",
          100: "#fffde6",
          50: "#fffef2",
        },
        dark: {
          DEFAULT: "#121212",
        },
        light: {
          DEFAULT: "#fafafa",
        },
        neutral: {
          DEFAULT: "#d4d4d4",
        },
        // Admin Theme (Indigo Nexus)
        admin: {
          surface: "#ffffff",
          "on-error-container": "#93000a",
          "on-tertiary-fixed": "#001e2f",
          error: "#ba1a1a",
          "surface-container-highest": "#dae2fd",
          "outline-variant": "#c7c4d8",
          outline: "#777587",
          "chart-indigo-low": "rgba(79, 70, 229, 0.15)",
          "tertiary-fixed": "#c9e6ff",
          "surface-container": "#eaedff",
          "primary-fixed-dim": "#c3c0ff",
          "error-container": "#ffdad6",
          "surface-variant": "#dae2fd",
          "on-secondary-fixed-variant": "#38485d",
          "success-accent": "#10b981",
          "surface-container-lowest": "#ffffff",
          secondary: "#505f76",
          "on-background": "#131b2e",
          primary: "#3525cd",
          "on-tertiary-container": "#b8e0ff",
          "on-primary-container": "#dad7ff",
          "inverse-primary": "#c3c0ff",
          "on-secondary-fixed": "#0b1c30",
          "sidebar-active-bg": "#f3f4ff",
          tertiary: "#004d70",
          "inverse-on-surface": "#eef0ff",
          "on-tertiary-fixed-variant": "#004c6e",
          "secondary-container": "#d0e1fb",
          "on-surface-variant": "#464555",
          "on-surface": "#131b2e",
          "on-secondary-container": "#54647a",
          "primary-container": "#4f46e5",
          "on-primary-fixed-variant": "#3323cc",
          "on-primary": "#ffffff",
          "on-error": "#ffffff",
          "secondary-fixed-dim": "#b7c8e1",
          "tertiary-container": "#006693",
          "surface-container-high": "#e2e7ff",
          "primary-fixed": "#e2dfff",
          "on-primary-fixed": "#0f0069",
          "tertiary-fixed-dim": "#89ceff",
          "surface-bright": "#faf8ff",
          "secondary-fixed": "#d3e4fe",
          background: "#f8fafc",
          "inverse-surface": "#283044",
          "on-secondary": "#ffffff",
          "surface-dim": "#d2d9f4",
          "on-tertiary": "#ffffff",
          "surface-tint": "#4d44e3",
          "surface-container-low": "#f2f3ff",
        }
      },
      spacing: {
        "admin-sidebar": "256px",
        "admin-sm": "8px",
        "admin-xl": "32px",
        "admin-lg": "24px",
        "admin-md": "16px",
        "admin-2xl": "48px",
        "admin-xs": "4px",
        "admin-gutter": "32px",
      },
      fontSize: {
        "admin-headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "admin-body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "admin-display-lg": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "admin-mono-label": ["10px", { lineHeight: "12px", fontWeight: "700" }],
        "admin-label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "admin-body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      keyframes: {
        shine: {
          "0%": { "background-position": "100%" },
          "100%": { "background-position": "-100%" },
        },
        gradient: {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
        glitch: {
          "0%": { "clip-path": "inset(20% 0 50% 0)" },
          "5%": { "clip-path": "inset(10% 0 60% 0)" },
          "10%": { "clip-path": "inset(15% 0 55% 0)" },
          "15%": { "clip-path": "inset(25% 0 35% 0)" },
          "20%": { "clip-path": "inset(30% 0 40% 0)" },
          "25%": { "clip-path": "inset(40% 0 20% 0)" },
          "30%": { "clip-path": "inset(10% 0 60% 0)" },
          "35%": { "clip-path": "inset(15% 0 55% 0)" },
          "40%": { "clip-path": "inset(25% 0 35% 0)" },
          "45%": { "clip-path": "inset(30% 0 40% 0)" },
          "50%": { "clip-path": "inset(20% 0 50% 0)" },
          "55%": { "clip-path": "inset(10% 0 60% 0)" },
          "60%": { "clip-path": "inset(15% 0 55% 0)" },
          "65%": { "clip-path": "inset(25% 0 35% 0)" },
          "70%": { "clip-path": "inset(30% 0 40% 0)" },
          "75%": { "clip-path": "inset(40% 0 20% 0)" },
          "80%": { "clip-path": "inset(20% 0 50% 0)" },
          "85%": { "clip-path": "inset(10% 0 60% 0)" },
          "90%": { "clip-path": "inset(15% 0 55% 0)" },
          "95%": { "clip-path": "inset(25% 0 35% 0)" },
          "100%": { "clip-path": "inset(30% 0 40% 0)" },
        },
        "star-movement-bottom": {
          "0%": { transform: "translate(0%, 0%)", opacity: "1" },
          "100%": { transform: "translate(-100%, 0%)", opacity: "0" },
        },
        "star-movement-top": {
          "0%": { transform: "translate(0%, 0%)", opacity: "1" },
          "100%": { transform: "translate(100%, 0%)", opacity: "0" },
        },
      },
      animation: {
        shine: "shine 5s linear infinite",
        gradient: "gradient 8s linear infinite",
        "glitch-after":
          "glitch var(--after-duration) infinite linear alternate-reverse",
        "glitch-before":
          "glitch var(--before-duration) infinite linear alternate-reverse",
        "star-movement-bottom":
          "star-movement-bottom linear infinite alternate",
        "star-movement-top": "star-movement-top linear infinite alternate",
      },
    },
  },
  plugins: [],
  darkMode: "class",
};
export default config;
