-- Master CMS Schema Migration

-- 1. Guestbook Table
CREATE TABLE IF NOT EXISTS "public"."Guestbook" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "email" text NOT NULL,
    "message" text NOT NULL,
    "isApproved" boolean DEFAULT false,
    "createdAt" timestamp with time zone DEFAULT now()
);

-- 2. Uses Table
CREATE TABLE IF NOT EXISTS "public"."Uses" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "category" text NOT NULL,
    "description" text NOT NULL,
    "url" text,
    "iconUrl" text,
    "createdAt" timestamp with time zone DEFAULT now()
);

-- 3. Link Table
CREATE TABLE IF NOT EXISTS "public"."Link" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" text NOT NULL,
    "url" text NOT NULL,
    "icon" text,
    "type" text DEFAULT 'social',
    "createdAt" timestamp with time zone DEFAULT now()
);

-- 4. Changelog Table
CREATE TABLE IF NOT EXISTS "public"."Changelog" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "version" text NOT NULL,
    "date" text NOT NULL,
    "description" text NOT NULL,
    "createdAt" timestamp with time zone DEFAULT now()
);

-- 5. PageContent Table (For dynamic text in Home, About, etc.)
CREATE TABLE IF NOT EXISTS "public"."PageContent" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "page" text NOT NULL,
    "locale" text NOT NULL,
    "key" text NOT NULL,
    "value" text NOT NULL,
    "createdAt" timestamp with time zone DEFAULT now()
);

-- Add Unique Constraint to PageContent to avoid duplicate keys per page and locale
ALTER TABLE "public"."PageContent" 
ADD CONSTRAINT unique_page_locale_key UNIQUE ("page", "locale", "key");

-- Insert initial data for Home Page (example)
INSERT INTO "public"."PageContent" ("page", "locale", "key", "value") VALUES
('home', 'id', 'intro', 'Halo, saya Ridho'),
('home', 'en', 'intro', 'Hello, I am Ridho')
ON CONFLICT ("page", "locale", "key") DO NOTHING;

-- Grant access to Anon/Authenticated (RLS)
GRANT ALL ON "public"."Guestbook" TO anon, authenticated;
GRANT ALL ON "public"."Uses" TO anon, authenticated;
GRANT ALL ON "public"."Link" TO anon, authenticated;
GRANT ALL ON "public"."Changelog" TO anon, authenticated;
GRANT ALL ON "public"."PageContent" TO anon, authenticated;
