create extension if not exists pgcrypto;

create table if not exists profile (
  id bigint generated by default as identity primary key,
  full_name text not null,
  title text,
  bio text,
  location text,
  email text,
  phone text,
  whatsapp_url text,
  cv_link text,
  avatar_url text,
  hero_image text,
  about_image text
);

create table if not exists experience (
  id bigint generated by default as identity primary key,
  company text not null,
  position text not null,
  period text not null,
  description text,
  sort_order integer not null default 0
);

create index if not exists experience_sort_order_idx on experience (sort_order);

create table if not exists education (
  id bigint generated by default as identity primary key,
  institution text not null,
  degree text not null,
  major text not null,
  period text not null,
  status text,
  sort_order integer not null default 0
);

create index if not exists education_sort_order_idx on education (sort_order);

create table if not exists skill (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  percentage integer not null,
  icon text
);

create table if not exists project (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text not null,
  content text,
  image_url text,
  demo_url text,
  repo_url text,
  tags text not null,
  category text not null default 'project',
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists project_created_at_idx on project (created_at desc);
create index if not exists project_featured_idx on project (featured);

create table if not exists service (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  icon text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists service_sort_order_idx on service (sort_order);

create table if not exists article (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  content text not null,
  image_url text,
  tags text,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists article_created_at_idx on article (created_at desc);
create index if not exists article_published_idx on article (published);

create table if not exists social (
  id bigint generated by default as identity primary key,
  platform text not null,
  url text not null,
  icon text not null,
  user_id bigint
);

create table if not exists award (
  id bigint generated by default as identity primary key,
  title text not null,
  organizer text not null,
  date text not null,
  description text,
  certificate_url text,
  category text,
  credential_id text
);

create table if not exists testimonial (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  message text not null,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists message (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists admin_user (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null
);

create or replace function set_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_service_updated_at on service;
create trigger set_service_updated_at before update on service
for each row execute function set_updated_at();

drop trigger if exists set_article_updated_at on article;
create trigger set_article_updated_at before update on article
for each row execute function set_updated_at();

